"""initial database schema

Revision ID: 715c87a9c745
Revises: 
Create Date: 2026-10-08 23:13:23.102795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '715c87a9c745'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots_cache',
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at > fetched_at', name='ck_robots_cache_expiration'),
    sa.PrimaryKeyConstraint('origin')
    )
    op.create_table('source',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('allowed_hosts', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('crawl_interval_seconds', sa.Integer(), server_default=sa.text('3600'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('website', 'rss', 'api')", name='ck_source_kind'),
    sa.CheckConstraint('crawl_interval_seconds > 0', name='ck_source_crawl_interval'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('crawl_target',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('fetch_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default=sa.text("'page'"), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_fetch_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_from_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("kind IN ('page', 'sitemap', 'rss', 'api')", name='ck_crawl_target_kind'),
    sa.CheckConstraint("state IN ('queued', 'leased', 'blocked', 'disabled')", name='ck_crawl_target_state'),
    sa.CheckConstraint('failure_count >= 0', name='ck_crawl_target_failure_count'),
    sa.ForeignKeyConstraint(['discovered_from_id'], ['crawl_target.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'normalized_url', name='uq_crawl_target_source_url')
    )
    op.create_index('ix_crawl_target_frontier', 'crawl_target', ['state', 'next_fetch_at', 'priority'], unique=False)
    op.create_index(op.f('ix_crawl_target_source_id'), 'crawl_target', ['source_id'], unique=False)
    op.create_table('crawl_attempt',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('crawl_target_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('bytes_received', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('success', 'failed', 'blocked', 'not_modified')", name='ck_crawl_attempt_outcome'),
    sa.CheckConstraint('bytes_received >= 0', name='ck_crawl_attempt_bytes'),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name='ck_crawl_attempt_time'),
    sa.CheckConstraint('http_status BETWEEN 100 AND 599', name='ck_crawl_attempt_http_status'),
    sa.ForeignKeyConstraint(['crawl_target_id'], ['crawl_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crawl_attempt_target_started', 'crawl_attempt', ['crawl_target_id', 'started_at'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('last_crawl_target_id', sa.BigInteger(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_crawl_target_id'], ['crawl_target.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_index(op.f('ix_document_source_id'), 'document', ['source_id'], unique=False)
    op.create_index('ix_document_type_published', 'document', ['document_type', 'published_at'], unique=False)
    op.create_table('search_index',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=False),
    sa.Column('indexed_hash', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('ix_search_index_vector', 'search_index', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_index_vector', table_name='search_index', postgresql_using='gin')
    op.drop_table('search_index')
    op.drop_index('ix_document_type_published', table_name='document')
    op.drop_index(op.f('ix_document_source_id'), table_name='document')
    op.drop_table('document')
    op.drop_index('ix_crawl_attempt_target_started', table_name='crawl_attempt')
    op.drop_table('crawl_attempt')
    op.drop_index(op.f('ix_crawl_target_source_id'), table_name='crawl_target')
    op.drop_index('ix_crawl_target_frontier', table_name='crawl_target')
    op.drop_table('crawl_target')
    op.drop_table('source')
    op.drop_table('robots_cache')
    # ### end Alembic commands ###
